packages:
    - packages/core/*
    - packages/config/*
    - packages/*

catalog:
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@eslint/compat": ^1.3.2
    "@eslint/js": ^9.36.0
    "@tailwindcss/postcss": ^4.1.12
    "@tanstack/react-router": ^1.141.4
    "@tanstack/router-devtools": ^1.141.2
    "@tanstack/router-plugin": ^1.141.2
    "@turbo/gen": ^2.5.6
    "@types/node": ^22.19.1
    "@types/react": ^19.1.13
    "@types/react-dom": ^19.1.9
    "@typescript-eslint/eslint-plugin": ^8.44.1
    "@typescript-eslint/parser": ^8.44.1
    "@vitejs/plugin-react": ^4.7.0
    autoprefixer: ^10.4.22
    dayjs: ^1.11.18
    eslint: ^9.36.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^16.4.0
    husky: ^9.1.7
    lightningcss: ^1.30.2
    lint-staged: ^16.1.5
    postcss: ^8.5.6
    prettier: ^3.6.2
    react: ^19.1.1
    react-dom: ^19.1.1
    tailwindcss: 3.4.17
    terser: ^5.44.0
    tsup: ^8.5.0
    turbo: ^2.5.6
    typescript: ^5.9.3
    typescript-eslint: ^8.44.1
    vite: ^6.4.1
